defaults:
  - data: dataset
  - preprocesamiento: limpieza
  - experimentos: bilstm
  - _self_

hydra:
  run:
    dir: experiments/${experimentos.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  job:
    chdir: true